// Generated by flutter_clean_arch_cli
// CreateCommand - Handles the `clean_arch create` command

import 'package:args/args.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:flutter_clean_arch_cli/src/generators/core_generator.dart';
import 'package:flutter_clean_arch_cli/src/generators/structure_generator.dart';

class CreateCommand {
  final Logger logger;

  CreateCommand({required this.logger});

  Future<void> run(ArgResults command) async {
    final parser = ArgParser()
      ..addOption('name', abbr: 'n', help: 'The name of the Flutter project.')
      ..addFlag('help', abbr: 'h', negatable: false);

    ArgResults args;
    try {
      args = parser.parse(command.arguments);
    } catch (e) {
      logger.err('Error: $e');
      _printUsage();
      return;
    }

    if (args['help'] as bool) {
      _printUsage();
      return;
    }

    final projectName = args['name'] as String?;
    if (projectName == null || projectName.isEmpty) {
      logger.err('Please provide a project name using --name or -n flag.');
      logger.info('Example: clean_arch create --name my_app');
      return;
    }

    // Validate project name
    if (!RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(projectName)) {
      logger.err(
        'Invalid project name. Use lowercase letters, numbers, and underscores only.\n'
        'Must start with a lowercase letter.',
      );
      return;
    }

    logger.info('''
╔══════════════════════════════════════════════════════╗
║         flutter_clean_arch_cli - Creating Project   ║
╚══════════════════════════════════════════════════════╝
''');

    final progress = logger.progress('Generating Clean Architecture for "$projectName"');

    try {
      // Generate folder structure
      await StructureGenerator(
        projectName: projectName,
        logger: logger,
      ).generate();

      // Generate core files
      await CoreGenerator(
        projectName: projectName,
        logger: logger,
      ).generate();

      progress.complete('Project structure created successfully! 🎉');

      logger.success('''

✅ Clean Architecture structure generated for "$projectName"

📁 Structure:
  lib/
  ├── core/
  │   ├── api/          → API client & interceptors
  │   ├── errors/       → Failures & exceptions
  │   ├── theme/        → App theme & colors
  │   ├── utils/        → Utilities & helpers
  │   ├── constants/    → App constants
  │   ├── di/           → Dependency injection
  │   └── network/      → Network info
  └── features/
      └── (your features go here)

🚀 Next Steps:
  1. Run: cd $projectName && flutter pub get
  2. Add your feature: clean_arch feature --name auth
  3. Configure your API base URL in core/constants/app_constants.dart
  4. Add your colors in core/theme/app_colors.dart
  5. Set up your DI in core/di/injection_container.dart

📦 Add these to your pubspec.yaml:
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dio: ^5.4.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
''');
    } catch (e) {
      progress.fail('Failed to generate project structure.');
      logger.err('Error: $e');
    }
  }

  void _printUsage() {
    logger.info('''
Usage: clean_arch create [options]

Options:
  -n, --name    The name of your Flutter project (required)
  -h, --help    Show this help message

Example:
  clean_arch create --name my_app
  clean_arch create -n shopping_app
''');
  }
}
