// Generated by flutter_clean_arch_cli
// FeatureCommand - Handles the `clean_arch feature` command

import 'package:args/args.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:flutter_clean_architecture_cli/src/generators/feature_generator.dart';

class FeatureCommand {
  final Logger logger;

  FeatureCommand({required this.logger});

  Future<void> run(ArgResults command) async {
    final parser = ArgParser()
      ..addOption('name', abbr: 'n', help: 'The name of the feature.')
      ..addFlag('help', abbr: 'h', negatable: false);

    ArgResults args;
    try {
      args = parser.parse(command.arguments);
    } catch (e) {
      logger.err('Error: $e');
      _printUsage();
      return;
    }

    if (args['help'] as bool) {
      _printUsage();
      return;
    }

    final featureName = args['name'] as String?;
    if (featureName == null || featureName.isEmpty) {
      logger.err('Please provide a feature name using --name or -n flag.');
      logger.info('Example: clean_arch feature --name auth');
      return;
    }

    if (!RegExp(r'^[a-z][a-z0-9_]*$').hasMatch(featureName)) {
      logger.err(
        'Invalid feature name. Use lowercase letters, numbers, and underscores only.\n'
        'Must start with a lowercase letter.',
      );
      return;
    }

    logger.info('''
╔══════════════════════════════════════════════════════╗
║         flutter_clean_arch_cli - Adding Feature     ║
╚══════════════════════════════════════════════════════╝
''');

    final progress = logger.progress('Generating feature "$featureName" with BLoC...');

    try {
      await FeatureGenerator(
        featureName: featureName,
        logger: logger,
      ).generate();

      progress.complete('Feature "$featureName" created successfully! 🎉');

      logger.success('''

✅ Feature "$featureName" generated!

📁 Structure:
  lib/features/$featureName/
  ├── data/
  │   ├── datasources/  → Remote & local data sources
  │   ├── models/       → Data models (fromJson/toJson)
  │   └── repositories/ → Repository implementations
  ├── domain/
  │   ├── entities/     → Business entities
  │   ├── repositories/ → Abstract repository contracts
  │   └── usecases/     → Business logic use cases
  └── presentation/
      ├── bloc/         → BLoC (events, states, bloc)
      ├── pages/        → UI pages/screens
      └── widgets/      → Reusable widgets

🚀 Next Steps:
  1. Define your entity in domain/entities/${featureName}_entity.dart
  2. Create your model in data/models/${featureName}_model.dart
  3. Implement your use cases in domain/usecases/
  4. Wire up your BLoC in presentation/bloc/
  5. Register dependencies in core/di/injection_container.dart
''');
    } catch (e) {
      progress.fail('Failed to generate feature.');
      logger.err('Error: $e');
    }
  }

  void _printUsage() {
    logger.info('''
Usage: clean_arch feature [options]

Options:
  -n, --name    The name of the feature (required)
  -h, --help    Show this help message

Example:
  clean_arch feature --name auth
  clean_arch feature --name home
  clean_arch feature --name product
''');
  }
}
