// Generated by flutter_clean_arch_cli
// VersionCommand - Shows CLI version info

import 'package:args/args.dart';
import 'package:mason_logger/mason_logger.dart';

class VersionCommand {
  final Logger logger;
  VersionCommand({required this.logger});

  Future<void> run(ArgResults command) async {
    logger.info('''
flutter_clean_arch_cli v1.0.0
Flutter Clean Architecture Generator CLI
https://pub.dev/packages/flutter_clean_arch_cli
''');
  }
}
