// Generated by flutter_clean_arch_cli
// CoreGenerator - Creates all core/ files

import 'dart:io';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;
import 'package:flutter_clean_arch_cli/src/templates/core_templates.dart';

class CoreGenerator {
  final String projectName;
  final Logger logger;

  CoreGenerator({required this.projectName, required this.logger});

  Future<void> generate() async {
    final base = p.join(Directory.current.path, projectName, 'lib', 'core');

    final files = {
      // API
      'api/api_client.dart': CoreTemplates.apiClient(projectName),
      'api/api_interceptor.dart': CoreTemplates.apiInterceptor(projectName),
      'api/api_endpoints.dart': CoreTemplates.apiEndpoints(projectName),
      // Errors
      'errors/failures.dart': CoreTemplates.failures(projectName),
      'errors/exceptions.dart': CoreTemplates.exceptions(projectName),
      // Theme
      'theme/app_colors.dart': CoreTemplates.appColors(projectName),
      'theme/app_text_styles.dart': CoreTemplates.appTextStyles(projectName),
      'theme/app_theme.dart': CoreTemplates.appTheme(projectName),
      // Utils
      'utils/app_utils.dart': CoreTemplates.appUtils(projectName),
      // Constants
      'constants/app_constants.dart': CoreTemplates.appConstants(projectName),
      // Network
      'network/network_info.dart': CoreTemplates.networkInfo(projectName),
      // DI
      'di/injection_container.dart': CoreTemplates.injectionContainer(projectName),
      // UseCase base
      'usecases/usecase.dart': CoreTemplates.useCase(projectName),
    };

    for (final entry in files.entries) {
      final filePath = p.join(base, entry.key);
      await File(filePath).writeAsString(entry.value);
    }
  }
}
