// Generated by flutter_clean_arch_cli
// FeatureGenerator - Creates all feature files with BLoC

import 'dart:io';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;
import 'package:flutter_clean_architecture_cli/src/templates/feature_templates.dart';
import 'package:flutter_clean_architecture_cli/src/utils/string_utils.dart';

class FeatureGenerator {
  final String featureName;
  final Logger logger;

  FeatureGenerator({required this.featureName, required this.logger});

  Future<void> generate() async {
    final base = p.join(
      Directory.current.path,
      'lib',
      'features',
      featureName,
    );

    final className = StringUtils.toClassName(featureName);

    final files = {
      // Data Layer
      'data/datasources/${featureName}_remote_datasource.dart':
          FeatureTemplates.remoteDataSource(featureName, className),
      'data/datasources/${featureName}_local_datasource.dart':
          FeatureTemplates.localDataSource(featureName, className),
      'data/models/${featureName}_model.dart':
          FeatureTemplates.model(featureName, className),
      'data/repositories/${featureName}_repository_impl.dart':
          FeatureTemplates.repositoryImpl(featureName, className),

      // Domain Layer
      'domain/entities/${featureName}_entity.dart':
          FeatureTemplates.entity(featureName, className),
      'domain/repositories/${featureName}_repository.dart':
          FeatureTemplates.repository(featureName, className),
      'domain/usecases/get_$featureName.dart':
          FeatureTemplates.useCase(featureName, className),

      // Presentation Layer
      'presentation/bloc/${featureName}_event.dart':
          FeatureTemplates.blocEvent(featureName, className),
      'presentation/bloc/${featureName}_state.dart':
          FeatureTemplates.blocState(featureName, className),
      'presentation/bloc/${featureName}_bloc.dart':
          FeatureTemplates.bloc(featureName, className),
      'presentation/pages/${featureName}_page.dart':
          FeatureTemplates.page(featureName, className),
      'presentation/widgets/${featureName}_widget.dart':
          FeatureTemplates.widget(featureName, className),
    };

    for (final entry in files.entries) {
      final filePath = p.join(base, entry.key);
      await File(filePath).create(recursive: true);
      await File(filePath).writeAsString(entry.value);
    }
  }
}
