// Generated by flutter_clean_arch_cli
// StructureGenerator - Creates top-level folder structure

import 'dart:io';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

class StructureGenerator {
  final String projectName;
  final Logger logger;

  StructureGenerator({required this.projectName, required this.logger});

  Future<void> generate() async {
    final basePath = p.join(Directory.current.path, projectName);

    final dirs = [
      // Core
      'lib/core/api',
      'lib/core/errors',
      'lib/core/theme',
      'lib/core/utils',
      'lib/core/constants',
      'lib/core/di',
      'lib/core/network',
      'lib/core/usecases',
      // Features placeholder
      'lib/features',
    ];

    for (final dir in dirs) {
      final fullPath = p.join(basePath, dir);
      await Directory(fullPath).create(recursive: true);
    }
  }
}
