// Generated by flutter_clean_arch_cli
// StringUtils - Helper methods for string transformations

class StringUtils {
  /// Converts snake_case to PascalCase (ClassName)
  /// e.g., "user_profile" → "UserProfile"
  static String toClassName(String snakeCase) {
    return snakeCase
        .split('_')
        .map((word) => word[0].toUpperCase() + word.substring(1))
        .join();
  }

  /// Converts snake_case to camelCase
  /// e.g., "user_profile" → "userProfile"
  static String toCamelCase(String snakeCase) {
    final parts = snakeCase.split('_');
    return parts[0] +
        parts.sublist(1).map((w) => w[0].toUpperCase() + w.substring(1)).join();
  }
}
