// Generated by flutter_clean_arch_cli
// CLI Runner - handles all commands and arguments

import 'package:args/args.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:flutter_clean_architecture_cli/src/commands/create_command.dart';
import 'package:flutter_clean_architecture_cli/src/commands/feature_command.dart';
import 'package:flutter_clean_architecture_cli/src/commands/version_command.dart';

/// The current version of the CLI.
const cliVersion = '1.1.0';

/// The main entry point for the CLI runner.
///
/// Parses the [arguments] and executes the corresponding commands.
Future<void> run(List<String> arguments) async {
  final logger = Logger();

  final parser = ArgParser()
    ..addCommand(
      'create',
      ArgParser()
        ..addOption('name', abbr: 'n', help: 'The name of the Flutter project.')
        ..addFlag('help', abbr: 'h', negatable: false),
    )
    ..addCommand(
      'feature',
      ArgParser()
        ..addOption('name', abbr: 'n', help: 'The name of the feature.')
        ..addFlag('help', abbr: 'h', negatable: false),
    )
    ..addCommand('version')
    ..addFlag('help', abbr: 'h', negatable: false, help: 'Show usage help.')
    ..addFlag('version', abbr: 'v', negatable: false, help: 'Show CLI version.');

  ArgResults results;
  try {
    results = parser.parse(arguments);
  } catch (e) {
    logger.err('Error parsing arguments: $e');
    _printUsage(logger);
    return;
  }

  if (results['version'] as bool) {
    logger.info('flutter_clean_arch_cli v$cliVersion');
    return;
  }

  if (results['help'] as bool || results.command == null) {
    _printUsage(logger);
    return;
  }

  final command = results.command!;

  switch (command.name) {
    case 'create':
      await CreateCommand(logger: logger).run(command);
      break;
    case 'feature':
      await FeatureCommand(logger: logger).run(command);
      break;
    case 'version':
      await VersionCommand(logger: logger).run(command);
      break;
    default:
      logger.err('Unknown command: ${command.name}');
      _printUsage(logger);
  }
}

void _printUsage(Logger logger) {
  logger.info('''
╔══════════════════════════════════════════════════════╗
║         flutter_clean_arch_cli v$cliVersion                ║
║     Flutter Clean Architecture Generator CLI        ║
╚══════════════════════════════════════════════════════╝

Usage: clean_arch <command> [arguments]

Available commands:
  create    Create a full clean architecture project structure
  feature   Add a new feature to an existing project
  version   Show the CLI version

Examples:
  clean_arch create --name my_app
  clean_arch feature --name auth
  clean_arch feature --name home

Flags:
  -h, --help       Show this help message
  -v, --version    Show CLI version

📦 Generated with flutter_clean_arch_cli
🔗 https://pub.dev/packages/flutter_clean_arch_cli
''');
}
