// ignore_for_file: unnecessary_brace_in_string_interps
// CoreTemplates - All template strings for core/ files

class CoreTemplates {
  // ─────────────────────────────────────────────
  // API CLIENT
  // ─────────────────────────────────────────────
  static String apiClient(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// ApiClient
// This file sets up the Dio HTTP client used across the app.
// TODO: Configure baseUrl in AppConstants.baseUrl
// ─────────────────────────────────────────────────────────────

import 'package:dio/dio.dart';
import '../constants/app_constants.dart';
import 'api_interceptor.dart';

class ApiClient {
  late final Dio _dio;

  ApiClient() {
    _dio = Dio(
      BaseOptions(
        // TODO: Replace with your API base URL from AppConstants
        baseUrl: AppConstants.baseUrl,
        connectTimeout: const Duration(seconds: AppConstants.connectTimeout),
        receiveTimeout: const Duration(seconds: AppConstants.receiveTimeout),
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
      ),
    );

    // Attach interceptors (logging, auth token injection, error handling)
    _dio.interceptors.add(ApiInterceptor());
  }

  Dio get dio => _dio;

  // GET request helper
  Future<Response> get(String path, {Map<String, dynamic>? queryParameters}) async {
    return _dio.get(path, queryParameters: queryParameters);
  }

  // POST request helper
  Future<Response> post(String path, {dynamic data}) async {
    return _dio.post(path, data: data);
  }

  // PUT request helper
  Future<Response> put(String path, {dynamic data}) async {
    return _dio.put(path, data: data);
  }

  // DELETE request helper
  Future<Response> delete(String path) async {
    return _dio.delete(path);
  }
}
''';

  // ─────────────────────────────────────────────
  // API INTERCEPTOR
  // ─────────────────────────────────────────────
  static String apiInterceptor(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// ApiInterceptor
// Intercepts every request and response.
// TODO: Add your auth token injection logic here
// TODO: Handle token refresh if needed
// ─────────────────────────────────────────────────────────────

import 'package:dio/dio.dart';

class ApiInterceptor extends Interceptor {
  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    // TODO: Inject your auth token here
    // Example:
    // final token = getIt<AuthLocalDataSource>().getToken();
    // if (token != null) {
    //   options.headers['Authorization'] = 'Bearer \$token';
    // }

    // Log request in debug mode
    // ignore: avoid_print
    print('[API REQUEST] \${options.method} \${options.uri}');

    handler.next(options);
  }

  @override
  void onResponse(Response response, ResponseInterceptorHandler handler) {
    // Log response
    // ignore: avoid_print
    print('[API RESPONSE] \${response.statusCode} \${response.requestOptions.uri}');
    handler.next(response);
  }

  @override
  void onError(DioException err, ErrorInterceptorHandler handler) {
    // TODO: Handle global errors like 401 Unauthorized (token refresh)
    // ignore: avoid_print
    print('[API ERROR] \${err.response?.statusCode} \${err.message}');
    handler.next(err);
  }
}
''';

  // ─────────────────────────────────────────────
  // API ENDPOINTS
  // ─────────────────────────────────────────────
  static String apiEndpoints(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// ApiEndpoints
// Centralizes all API endpoint paths.
// TODO: Add your API endpoints here
// ─────────────────────────────────────────────────────────────

class ApiEndpoints {
  ApiEndpoints._();

  // Auth endpoints
  // TODO: Add your actual endpoint paths
  static const String login = '/auth/login';
  static const String register = '/auth/register';
  static const String logout = '/auth/logout';
  static const String refreshToken = '/auth/refresh';

  // User endpoints
  static const String getUser = '/users/me';
  static const String updateUser = '/users/me';

  // TODO: Add more endpoints for your features below
  // Example:
  // static const String getProducts = '/products';
  // static const String getProductById = '/products/{id}';
}
''';

  // ─────────────────────────────────────────────
  // FAILURES
  // ─────────────────────────────────────────────
  static String failures(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// Failures
// Represents domain-level failures returned from use cases.
// Used with Either<Failure, T> from dartz package.
// ─────────────────────────────────────────────────────────────

import 'package:equatable/equatable.dart';

/// Base class for all failures in the app.
abstract class Failure extends Equatable {
  final String message;
  const Failure({required this.message});

  @override
  List<Object> get props => [message];
}

/// Failure for server-side errors (4xx, 5xx responses).
class ServerFailure extends Failure {
  const ServerFailure({required super.message});
}

/// Failure when the device has no internet connection.
class NetworkFailure extends Failure {
  const NetworkFailure({required super.message});
}

/// Failure for local cache/storage errors.
class CacheFailure extends Failure {
  const CacheFailure({required super.message});
}

/// Failure for authentication errors (401, 403).
class AuthFailure extends Failure {
  const AuthFailure({required super.message});
}

/// Failure when a requested item is not found (404).
class NotFoundFailure extends Failure {
  const NotFoundFailure({required super.message});
}

// TODO: Add custom failures specific to your domain below
// Example:
// class ValidationFailure extends Failure {
//   const ValidationFailure({required super.message});
// }
''';

  // ─────────────────────────────────────────────
  // EXCEPTIONS
  // ─────────────────────────────────────────────
  static String exceptions(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// Exceptions
// Data-layer exceptions that get converted to Failures.
// These are caught in repository implementations.
// ─────────────────────────────────────────────────────────────

/// Thrown when the remote API returns an error response.
class ServerException implements Exception {
  final String message;
  final int? statusCode;

  const ServerException({required this.message, this.statusCode});

  @override
  String toString() => 'ServerException: \$message (statusCode: \$statusCode)';
}

/// Thrown when there is no internet connection.
class NetworkException implements Exception {
  final String message;
  const NetworkException({this.message = 'No internet connection.'});

  @override
  String toString() => 'NetworkException: \$message';
}

/// Thrown when reading/writing to local cache fails.
class CacheException implements Exception {
  final String message;
  const CacheException({required this.message});

  @override
  String toString() => 'CacheException: \$message';
}

/// Thrown when authentication fails.
class AuthException implements Exception {
  final String message;
  const AuthException({required this.message});

  @override
  String toString() => 'AuthException: \$message';
}

// TODO: Add more custom exceptions for your features below
''';

  // ─────────────────────────────────────────────
  // APP COLORS
  // ─────────────────────────────────────────────
  static String appColors(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// AppColors
// TODO: Replace these placeholder colors with your brand colors.
// TIP: Use a tool like https://m3.material.io/theme-builder to generate a palette.
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  // ── Primary Brand Colors ──────────────────────────────────
  // TODO: Replace with your primary brand color
  static const Color primary = Color(0xFF6200EE);
  static const Color primaryVariant = Color(0xFF3700B3);
  static const Color onPrimary = Color(0xFFFFFFFF);

  // ── Secondary Brand Colors ────────────────────────────────
  // TODO: Replace with your secondary brand color
  static const Color secondary = Color(0xFF03DAC6);
  static const Color secondaryVariant = Color(0xFF018786);
  static const Color onSecondary = Color(0xFF000000);

  // ── Background & Surface ──────────────────────────────────
  // TODO: Adjust to match your app's background style
  static const Color background = Color(0xFFF5F5F5);
  static const Color surface = Color(0xFFFFFFFF);
  static const Color onBackground = Color(0xFF000000);
  static const Color onSurface = Color(0xFF000000);

  // ── Error Colors ──────────────────────────────────────────
  static const Color error = Color(0xFFB00020);
  static const Color onError = Color(0xFFFFFFFF);

  // ── Text Colors ───────────────────────────────────────────
  // TODO: Add your text colors
  static const Color textPrimary = Color(0xFF212121);
  static const Color textSecondary = Color(0xFF757575);
  static const Color textHint = Color(0xFFBDBDBD);
  static const Color textDisabled = Color(0xFF9E9E9E);

  // ── Status Colors ─────────────────────────────────────────
  static const Color success = Color(0xFF4CAF50);
  static const Color warning = Color(0xFFFFC107);
  static const Color info = Color(0xFF2196F3);

  // ── Misc ──────────────────────────────────────────────────
  static const Color divider = Color(0xFFE0E0E0);
  static const Color shadow = Color(0x1A000000);
  static const Color transparent = Colors.transparent;

  // TODO: Add more colors specific to your app
}
''';

  // ─────────────────────────────────────────────
  // APP TEXT STYLES
  // ─────────────────────────────────────────────
  static String appTextStyles(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// AppTextStyles
// TODO: Replace the font family with your chosen font.
// Add your font to pubspec.yaml under flutter > fonts.
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import 'app_colors.dart';

class AppTextStyles {
  AppTextStyles._();

  // TODO: Replace 'Roboto' with your custom font family name
  static const String _fontFamily = 'Roboto';

  // ── Headings ──────────────────────────────────────────────
  static const TextStyle h1 = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 32,
    fontWeight: FontWeight.bold,
    color: AppColors.textPrimary,
  );

  static const TextStyle h2 = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 24,
    fontWeight: FontWeight.bold,
    color: AppColors.textPrimary,
  );

  static const TextStyle h3 = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 20,
    fontWeight: FontWeight.w600,
    color: AppColors.textPrimary,
  );

  // ── Body ──────────────────────────────────────────────────
  static const TextStyle bodyLarge = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 16,
    fontWeight: FontWeight.normal,
    color: AppColors.textPrimary,
  );

  static const TextStyle bodyMedium = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 14,
    fontWeight: FontWeight.normal,
    color: AppColors.textPrimary,
  );

  static const TextStyle bodySmall = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 12,
    fontWeight: FontWeight.normal,
    color: AppColors.textSecondary,
  );

  // ── Button ────────────────────────────────────────────────
  static const TextStyle button = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 16,
    fontWeight: FontWeight.w600,
    color: AppColors.onPrimary,
    letterSpacing: 0.5,
  );

  // ── Caption ───────────────────────────────────────────────
  static const TextStyle caption = TextStyle(
    fontFamily: _fontFamily,
    fontSize: 11,
    fontWeight: FontWeight.normal,
    color: AppColors.textSecondary,
  );

  // TODO: Add more text styles as your design requires
}
''';

  // ─────────────────────────────────────────────
  // APP THEME
  // ─────────────────────────────────────────────
  static String appTheme(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// AppTheme
// Configures the app's light and dark themes.
// TODO: Customize the theme to match your design system.
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import 'app_colors.dart';
import 'app_text_styles.dart';

class AppTheme {
  AppTheme._();

  /// Light theme configuration
  static ThemeData get lightTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      primaryColor: AppColors.primary,
      scaffoldBackgroundColor: AppColors.background,
      colorScheme: const ColorScheme.light(
        primary: AppColors.primary,
        secondary: AppColors.secondary,
        error: AppColors.error,
        surface: AppColors.surface,
      ),
      // TODO: Customize AppBar theme to match your brand
      appBarTheme: const AppBarTheme(
        backgroundColor: AppColors.primary,
        foregroundColor: AppColors.onPrimary,
        elevation: 0,
        titleTextStyle: AppTextStyles.h3,
      ),
      // TODO: Customize ElevatedButton theme
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: AppColors.primary,
          foregroundColor: AppColors.onPrimary,
          textStyle: AppTextStyles.button,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
        ),
      ),
      // TODO: Customize InputDecoration theme for text fields
      inputDecorationTheme: InputDecorationTheme(
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: AppColors.primary, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: AppColors.error),
        ),
        hintStyle: AppTextStyles.bodyMedium.copyWith(color: AppColors.textHint),
      ),
      dividerColor: AppColors.divider,
      textTheme: const TextTheme(
        displayLarge: AppTextStyles.h1,
        displayMedium: AppTextStyles.h2,
        titleLarge: AppTextStyles.h3,
        bodyLarge: AppTextStyles.bodyLarge,
        bodyMedium: AppTextStyles.bodyMedium,
        bodySmall: AppTextStyles.bodySmall,
        labelLarge: AppTextStyles.button,
      ),
    );
  }

  /// Dark theme configuration
  /// TODO: Configure dark theme colors
  static ThemeData get darkTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.dark,
      primaryColor: AppColors.primary,
      colorScheme: const ColorScheme.dark(
        primary: AppColors.primary,
        secondary: AppColors.secondary,
        error: AppColors.error,
      ),
      // TODO: Customize dark theme components
    );
  }
}
''';

  // ─────────────────────────────────────────────
  // APP UTILS
  // ─────────────────────────────────────────────
  static String appUtils(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// AppUtils
// General utility functions used across the app.
// TODO: Add your own utility methods here.
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';

class AppUtils {
  AppUtils._();

  /// Shows a SnackBar with a message.
  static void showSnackBar(BuildContext context, String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: isError ? Colors.red : Colors.green,
        behavior: SnackBarBehavior.floating,
        duration: const Duration(seconds: 3),
      ),
    );
  }

  /// Shows a loading dialog.
  static void showLoadingDialog(BuildContext context) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (_) => const Center(child: CircularProgressIndicator()),
    );
  }

  /// Dismisses an open dialog.
  static void dismissDialog(BuildContext context) {
    if (Navigator.of(context).canPop()) {
      Navigator.of(context).pop();
    }
  }

  /// Formats a DateTime to a readable string.
  /// TODO: Customize date format as needed
  static String formatDate(DateTime date) {
    return '\${date.day}/\${date.month}/\${date.year}';
  }

  /// Validates an email address format.
  static bool isValidEmail(String email) {
    return RegExp(r'^[\\w-.]+@([\\w-]+\\.)+[\\w-]{2,4}\$').hasMatch(email);
  }

  /// Checks if a string is null or empty.
  static bool isNullOrEmpty(String? value) {
    return value == null || value.trim().isEmpty;
  }

  // TODO: Add more utility methods specific to your app
}
''';

  // ─────────────────────────────────────────────
  // APP CONSTANTS
  // ─────────────────────────────────────────────
  static String appConstants(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// AppConstants
// Central place for all app-wide constants.
// TODO: Fill in your actual API URL and keys.
// ─────────────────────────────────────────────────────────────

class AppConstants {
  AppConstants._();

  // ── API Configuration ─────────────────────────────────────
  // TODO: Replace with your actual API base URL
  static const String baseUrl = 'https://your-api.com/api/v1';

  // TODO: Set appropriate timeout values for your API
  static const int connectTimeout = 30; // seconds
  static const int receiveTimeout = 30; // seconds

  // ── App Info ──────────────────────────────────────────────
  static const String appName = '$projectName';

  // TODO: Update version to match pubspec.yaml
  static const String appVersion = '1.0.0';

  // ── Local Storage Keys ────────────────────────────────────
  // TODO: Add your SharedPreferences / Hive keys here
  static const String tokenKey = 'auth_token';
  static const String refreshTokenKey = 'refresh_token';
  static const String userKey = 'user_data';
  static const String themeKey = 'app_theme';

  // ── Pagination ────────────────────────────────────────────
  // TODO: Adjust to match your API's pagination settings
  static const int pageSize = 20;
  static const int firstPage = 1;

  // ── Durations ─────────────────────────────────────────────
  static const Duration splashDuration = Duration(seconds: 2);
  static const Duration animationDuration = Duration(milliseconds: 300);

  // TODO: Add more constants specific to your app
}
''';

  // ─────────────────────────────────────────────
  // NETWORK INFO
  // ─────────────────────────────────────────────
  static String networkInfo(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// NetworkInfo
// Checks whether the device has an active internet connection.
// Uses internet_connection_checker package.
// ─────────────────────────────────────────────────────────────

import 'package:internet_connection_checker/internet_connection_checker.dart';

/// Abstract contract for network info
abstract class NetworkInfo {
  Future<bool> get isConnected;
}

/// Implementation using internet_connection_checker
class NetworkInfoImpl implements NetworkInfo {
  final InternetConnectionChecker connectionChecker;

  NetworkInfoImpl(this.connectionChecker);

  @override
  Future<bool> get isConnected => connectionChecker.hasConnection;
}
''';

  // ─────────────────────────────────────────────
  // INJECTION CONTAINER (DI)
  // ─────────────────────────────────────────────
  static String injectionContainer(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// InjectionContainer (Dependency Injection)
// Uses get_it as a service locator.
// TODO: Register all your dependencies here.
// TODO: Call init() from main.dart before runApp().
// ─────────────────────────────────────────────────────────────

import 'package:get_it/get_it.dart';
import 'package:internet_connection_checker/internet_connection_checker.dart';
import '../api/api_client.dart';
import '../network/network_info.dart';

/// Global service locator instance
final GetIt getIt = GetIt.instance;

/// Initialize all dependencies.
/// Call this in main.dart: await init();
Future<void> init() async {
  // ── External Dependencies ─────────────────────────────────
  getIt.registerLazySingleton(() => InternetConnectionChecker());

  // ── Core ──────────────────────────────────────────────────
  getIt.registerLazySingleton<NetworkInfo>(
    () => NetworkInfoImpl(getIt()),
  );
  getIt.registerLazySingleton(() => ApiClient());

  // ── Features ──────────────────────────────────────────────
  // TODO: Register your feature dependencies below.
  // Follow this pattern for each feature:

  // BLoC
  // getIt.registerFactory(
  //   () => AuthBloc(loginUseCase: getIt()),
  // );

  // Use Cases
  // getIt.registerLazySingleton(() => LoginUseCase(getIt()));

  // Repository
  // getIt.registerLazySingleton<AuthRepository>(
  //   () => AuthRepositoryImpl(
  //     remoteDataSource: getIt(),
  //     localDataSource: getIt(),
  //     networkInfo: getIt(),
  //   ),
  // );

  // Data Sources
  // getIt.registerLazySingleton<AuthRemoteDataSource>(
  //   () => AuthRemoteDataSourceImpl(apiClient: getIt()),
  // );
  // getIt.registerLazySingleton<AuthLocalDataSource>(
  //   () => AuthLocalDataSourceImpl(),
  // );
}
''';

  // ─────────────────────────────────────────────
  // USE CASE BASE
  // ─────────────────────────────────────────────
  static String useCase(String projectName) => '''
// Generated by flutter_clean_arch_cli
// ─────────────────────────────────────────────────────────────
// UseCase Base Class
// All use cases in the domain layer extend this class.
// Uses Either<Failure, Type> from dartz for error handling.
// ─────────────────────────────────────────────────────────────

import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';
import '../errors/failures.dart';

/// Base use case with params.
/// [Type] is the success return type.
/// [Params] is the input parameter type.
abstract class UseCase<Type, Params> {
  Future<Either<Failure, Type>> call(Params params);
}

/// Use this when a use case has no parameters.
class NoParams extends Equatable {
  @override
  List<Object> get props => [];
}
''';
}
