// Generated by flutter_clean_architecture_cli
// FeatureTemplates - All template strings for feature/ files

class FeatureTemplates {
  // ─────────────────────────────────────────────
  // DATA LAYER - Remote DataSource
  // ─────────────────────────────────────────────
  static String remoteDataSource(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}RemoteDataSource
// Responsible for fetching data from the remote API.
// TODO: Implement the actual API calls using ApiClient.
// ─────────────────────────────────────────────────────────────

import '../../../core/api/api_client.dart';
import '../../../core/api/api_endpoints.dart';
import '../../../core/errors/exceptions.dart';
import '../models/${name}_model.dart';

/// Abstract contract for the remote data source.
abstract class ${className}RemoteDataSource {
  /// Fetches $name data from the remote API.
  /// Throws [ServerException] on failure.
  Future<${className}Model> get$className();

  // TODO: Add more remote methods as needed
  // Example: Future<void> create$className(${className}Model model);
}

/// Implementation of [${className}RemoteDataSource].
class ${className}RemoteDataSourceImpl implements ${className}RemoteDataSource {
  final ApiClient apiClient;

  ${className}RemoteDataSourceImpl({required this.apiClient});

  @override
  Future<${className}Model> get$className() async {
    try {
      // TODO: Replace with your actual endpoint from ApiEndpoints
      final response = await apiClient.get(ApiEndpoints.getUser);

      if (response.statusCode == 200) {
        return ${className}Model.fromJson(response.data as Map<String, dynamic>);
      } else {
        throw ServerException(
          message: 'Failed to fetch $name data.',
          statusCode: response.statusCode,
        );
      }
    } catch (e) {
      throw ServerException(message: e.toString());
    }
  }

  // TODO: Implement additional API methods here
}
''';

  // ─────────────────────────────────────────────
  // DATA LAYER - Local DataSource
  // ─────────────────────────────────────────────
  static String localDataSource(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}LocalDataSource
// Responsible for reading/writing data to local cache.
// TODO: Implement using SharedPreferences, Hive, or SQLite.
// ─────────────────────────────────────────────────────────────

import '../../../core/errors/exceptions.dart';
import '../models/${name}_model.dart';

/// Abstract contract for the local data source.
abstract class ${className}LocalDataSource {
  /// Gets the cached [${className}Model].
  /// Throws [CacheException] if no cached data exists.
  Future<${className}Model> getCached$className();

  /// Caches a [${className}Model] locally.
  Future<void> cache$className(${className}Model model);

  // TODO: Add more local storage methods as needed
}

/// Implementation of [${className}LocalDataSource].
class ${className}LocalDataSourceImpl implements ${className}LocalDataSource {
  // TODO: Inject SharedPreferences / Hive Box here
  // Example: final SharedPreferences sharedPreferences;
  // ${className}LocalDataSourceImpl({required this.sharedPreferences});

  static const String _cacheKey = 'CACHED_${name.toUpperCase()}';

  @override
  Future<${className}Model> getCached$className() async {
    // TODO: Implement cache retrieval
    // Example with SharedPreferences:
    // final jsonString = sharedPreferences.getString(_cacheKey);
    // if (jsonString != null) {
    //   return ${className}Model.fromJson(json.decode(jsonString));
    // }
    throw const CacheException(message: 'No cached $name data found.');
  }

  @override
  Future<void> cache$className(${className}Model model) async {
    // TODO: Implement cache saving
    // Example with SharedPreferences:
    // await sharedPreferences.setString(
    //   _cacheKey,
    //   json.encode(model.toJson()),
    // );
  }
}
''';

  // ─────────────────────────────────────────────
  // DATA LAYER - Model
  // ─────────────────────────────────────────────
  static String model(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}Model
// Data Transfer Object (DTO) for the $className feature.
// Extends ${className}Entity and handles JSON serialization.
// TODO: Add fields matching your API response structure.
// ─────────────────────────────────────────────────────────────

import '../../domain/entities/${name}_entity.dart';

class ${className}Model extends ${className}Entity {
  const ${className}Model({
    required super.id,
    // TODO: Add more fields that match your API response
    // required super.title,
    // required super.description,
  });

  /// Creates a [${className}Model] from a JSON map.
  /// TODO: Update field names to match your actual API response keys.
  factory ${className}Model.fromJson(Map<String, dynamic> json) {
    return ${className}Model(
      id: json['id'] as String? ?? '',
      // TODO: Map your JSON fields
      // title: json['title'] as String? ?? '',
      // description: json['description'] as String? ?? '',
    );
  }

  /// Converts this model to a JSON map for API requests.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      // TODO: Add your fields
      // 'title': title,
      // 'description': description,
    };
  }

  /// Creates a copy of this model with optional field overrides.
  ${className}Model copyWith({
    String? id,
    // TODO: Add copyWith parameters for all fields
  }) {
    return ${className}Model(
      id: id ?? this.id,
      // TODO: Add fields
    );
  }
}
''';

  // ─────────────────────────────────────────────
  // DATA LAYER - Repository Implementation
  // ─────────────────────────────────────────────
  static String repositoryImpl(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}RepositoryImpl
// Implements the domain repository contract.
// Handles network check, remote fetch, and local caching.
// ─────────────────────────────────────────────────────────────

import 'package:dartz/dartz.dart';
import '../../../core/errors/exceptions.dart';
import '../../../core/errors/failures.dart';
import '../../../core/network/network_info.dart';
import '../../domain/entities/${name}_entity.dart';
import '../../domain/repositories/${name}_repository.dart';
import '../datasources/${name}_local_datasource.dart';
import '../datasources/${name}_remote_datasource.dart';

class ${className}RepositoryImpl implements ${className}Repository {
  final ${className}RemoteDataSource remoteDataSource;
  final ${className}LocalDataSource localDataSource;
  final NetworkInfo networkInfo;

  ${className}RepositoryImpl({
    required this.remoteDataSource,
    required this.localDataSource,
    required this.networkInfo,
  });

  @override
  Future<Either<Failure, ${className}Entity>> get$className() async {
    if (await networkInfo.isConnected) {
      // Device is online — fetch from remote
      try {
        final remote = await remoteDataSource.get$className();

        // Cache the fresh data locally
        await localDataSource.cache$className(remote);

        return Right(remote);
      } on ServerException catch (e) {
        return Left(ServerFailure(message: e.message));
      } on AuthException catch (e) {
        return Left(AuthFailure(message: e.message));
      }
    } else {
      // Device is offline — return cached data
      try {
        final cached = await localDataSource.getCached$className();
        return Right(cached);
      } on CacheException catch (e) {
        return Left(CacheFailure(message: e.message));
      }
    }
  }

  // TODO: Implement other repository methods here
}
''';

  // ─────────────────────────────────────────────
  // DOMAIN LAYER - Entity
  // ─────────────────────────────────────────────
  static String entity(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}Entity
// The core business entity for the $className feature.
// This is pure Dart — no dependency on Flutter or external packages
// beyond equatable.
// TODO: Add fields that represent your business object.
// ─────────────────────────────────────────────────────────────

import 'package:equatable/equatable.dart';

class ${className}Entity extends Equatable {
  final String id;

  // TODO: Add your entity fields here
  // Example:
  // final String title;
  // final String description;
  // final DateTime createdAt;
  // final bool isActive;

  const ${className}Entity({
    required this.id,
    // TODO: Add required fields
    // required this.title,
    // required this.description,
    // required this.createdAt,
    // this.isActive = true,
  });

  @override
  List<Object?> get props => [
    id,
    // TODO: Add all fields to props for equality checks
    // title,
    // description,
    // createdAt,
    // isActive,
  ];
}
''';

  // ─────────────────────────────────────────────
  // DOMAIN LAYER - Repository (abstract)
  // ─────────────────────────────────────────────
  static String repository(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}Repository (Abstract)
// Defines the contract that the data layer must implement.
// The domain layer depends only on this abstract class.
// ─────────────────────────────────────────────────────────────

import 'package:dartz/dartz.dart';
import '../../../core/errors/failures.dart';
import '../entities/${name}_entity.dart';

abstract class ${className}Repository {
  /// Returns [${className}Entity] on success, [Failure] on error.
  Future<Either<Failure, ${className}Entity>> get$className();

  // TODO: Add more repository method signatures as needed
  // Example:
  // Future<Either<Failure, Unit>> create$className(${className}Entity entity);
  // Future<Either<Failure, List<${className}Entity>>> getAll${className}s();
  // Future<Either<Failure, Unit>> delete$className(String id);
}
''';

  // ─────────────────────────────────────────────
  // DOMAIN LAYER - UseCase
  // ─────────────────────────────────────────────
  static String useCase(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// Get${className}UseCase
// Encapsulates the business logic for fetching $name data.
// Called from the BLoC — never call the repository directly from UI.
// ─────────────────────────────────────────────────────────────

import 'package:dartz/dartz.dart';
import '../../../core/errors/failures.dart';
import '../../../core/usecases/usecase.dart';
import '../entities/${name}_entity.dart';
import '../repositories/${name}_repository.dart';

class Get${className}UseCase implements UseCase<${className}Entity, NoParams> {
  final ${className}Repository repository;

  Get${className}UseCase(this.repository);

  @override
  Future<Either<Failure, ${className}Entity>> call(NoParams params) async {
    return await repository.get$className();
  }
}

// TODO: Create additional use cases for this feature
// Pattern: one use case per operation
// Example:
// class Create${className}UseCase implements UseCase<Unit, ${className}Entity> { ... }
// class Delete${className}UseCase implements UseCase<Unit, String> { ... }
''';

  // ─────────────────────────────────────────────
  // PRESENTATION LAYER - BLoC Event
  // ─────────────────────────────────────────────
  static String blocEvent(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}Event
// Defines all possible events (user actions / triggers) for
// the ${className}Bloc.
// TODO: Add events matching your feature's interactions.
// ─────────────────────────────────────────────────────────────

part of '${name}_bloc.dart';

/// Base class for all $className events.
abstract class ${className}Event extends Equatable {
  const ${className}Event();

  @override
  List<Object?> get props => [];
}

/// Event to load $name data.
/// Dispatch this event to trigger a data fetch.
class Get${className}Event extends ${className}Event {
  const Get${className}Event();
}

// TODO: Add more events for your feature
// Examples:
// class Refresh${className}Event extends ${className}Event {
//   const Refresh${className}Event();
// }
//
// class Update${className}Event extends ${className}Event {
//   final ${className}Entity entity;
//   const Update${className}Event(this.entity);
//   @override
//   List<Object?> get props => [entity];
// }
//
// class Reset${className}Event extends ${className}Event {
//   const Reset${className}Event();
// }
''';

  // ─────────────────────────────────────────────
  // PRESENTATION LAYER - BLoC State
  // ─────────────────────────────────────────────
  static String blocState(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}State
// Defines all possible states that ${className}Bloc can emit.
// The UI listens to these states and rebuilds accordingly.
// ─────────────────────────────────────────────────────────────

part of '${name}_bloc.dart';

/// Base class for all $className states.
abstract class ${className}State extends Equatable {
  const ${className}State();

  @override
  List<Object?> get props => [];
}

/// Initial state — nothing has happened yet.
class ${className}Initial extends ${className}State {
  const ${className}Initial();
}

/// State while data is being fetched.
/// Show a loading spinner in this state.
class ${className}Loading extends ${className}State {
  const ${className}Loading();
}

/// State when data has been loaded successfully.
/// TODO: Render your UI using the [entity] field.
class ${className}Loaded extends ${className}State {
  final ${className}Entity entity;

  const ${className}Loaded({required this.entity});

  @override
  List<Object?> get props => [entity];
}

/// State when an error has occurred.
/// TODO: Show an error message using the [message] field.
class ${className}Error extends ${className}State {
  final String message;

  const ${className}Error({required this.message});

  @override
  List<Object?> get props => [message];
}

// TODO: Add more states if your feature needs them
// Examples:
// class ${className}Empty extends ${className}State {
//   const ${className}Empty();
// }
//
// class ${className}Refreshing extends ${className}State {
//   final ${className}Entity currentEntity;
//   const ${className}Refreshing({required this.currentEntity});
//   @override
//   List<Object?> get props => [currentEntity];
// }
''';

  // ─────────────────────────────────────────────
  // PRESENTATION LAYER - BLoC
  // ─────────────────────────────────────────────
  static String bloc(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}Bloc
// Bridges the domain use cases with the UI.
// Listens to events → calls use cases → emits states.
// TODO: Wire up your use cases in the constructor.
// ─────────────────────────────────────────────────────────────

import 'package:equatable/equatable.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../core/usecases/usecase.dart';
import '../../domain/entities/${name}_entity.dart';
import '../../domain/usecases/get_$name.dart';

part '${name}_event.dart';
part '${name}_state.dart';

class ${className}Bloc extends Bloc<${className}Event, ${className}State> {
  final Get${className}UseCase get$className;

  // TODO: Inject all use cases this BLoC depends on
  ${className}Bloc({
    required this.get$className,
    // TODO: Add more use cases
    // required this.create$className,
    // required this.delete$className,
  }) : super(const ${className}Initial()) {
    // Register event handlers
    on<Get${className}Event>(_onGet$className);

    // TODO: Register handlers for additional events
    // on<Update${className}Event>(_onUpdate$className);
    // on<Refresh${className}Event>(_onRefresh$className);
  }

  /// Handles [Get${className}Event] — fetches data and emits loading/loaded/error.
  Future<void> _onGet$className(
    Get${className}Event event,
    Emitter<${className}State> emit,
  ) async {
    emit(const ${className}Loading());

    final result = await get$className(NoParams());

    result.fold(
      // On failure — emit error with the failure message
      (failure) => emit(${className}Error(message: failure.message)),
      // On success — emit loaded with the entity
      (entity) => emit(${className}Loaded(entity: entity)),
    );
  }

  // TODO: Implement handlers for additional events
  // Example:
  // Future<void> _onUpdate$className(
  //   Update${className}Event event,
  //   Emitter<${className}State> emit,
  // ) async {
  //   emit(const ${className}Loading());
  //   final result = await update$className(event.entity);
  //   result.fold(
  //     (failure) => emit(${className}Error(message: failure.message)),
  //     (_) => add(const Get${className}Event()),
  //   );
  // }
}
''';

  // ─────────────────────────────────────────────
  // PRESENTATION LAYER - Page
  // ─────────────────────────────────────────────
  static String page(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}Page
// Main screen for the $className feature.
// Provides the BLoC via BlocProvider and builds UI from states.
// TODO: Customize the UI to match your design.
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/di/injection_container.dart';
import '../bloc/${name}_bloc.dart';
import '../widgets/${name}_widget.dart';

class ${className}Page extends StatelessWidget {
  const ${className}Page({super.key});

  // TODO: Update route name to match your app's routing strategy
  static const String routeName = '/$name';

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      // Provide the BLoC and trigger initial data fetch
      create: (_) => getIt<${className}Bloc>()..add(const Get${className}Event()),
      child: const ${className}View(),
    );
  }
}

class ${className}View extends StatelessWidget {
  const ${className}View({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // TODO: Update title to match your feature
        title: const Text('$className'),
      ),
      body: BlocConsumer<${className}Bloc, ${className}State>(
        // Listen for side effects (navigation, snackbars, dialogs)
        listener: (context, state) {
          if (state is ${className}Error) {
            // TODO: Customize error handling
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(state.message),
                backgroundColor: Colors.red,
              ),
            );
          }
          // TODO: Handle other states for side effects
          // Example: Navigate after success
          // if (state is ${className}Loaded) {
          //   Navigator.pushNamed(context, SomeOtherPage.routeName);
          // }
        },
        // Build UI based on current state
        builder: (context, state) {
          if (state is ${className}Loading) {
            // TODO: Customize loading indicator
            return const Center(child: CircularProgressIndicator());
          }

          if (state is ${className}Loaded) {
            // TODO: Pass entity to your widget and build your UI
            return ${className}Widget(entity: state.entity);
          }

          if (state is ${className}Error) {
            // TODO: Customize error UI
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.error_outline, color: Colors.red, size: 48),
                  const SizedBox(height: 16),
                  Text(
                    state.message,
                    textAlign: TextAlign.center,
                    style: Theme.of(context).textTheme.bodyMedium,
                  ),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    // Retry button — dispatches the event again
                    onPressed: () => context
                        .read<${className}Bloc>()
                        .add(const Get${className}Event()),
                    child: const Text('Retry'),
                  ),
                ],
              ),
            );
          }

          // Initial state
          return const Center(
            child: Text('Press the button to load data.'),
          );
        },
      ),
      // TODO: Add FAB or other actions as needed
      // floatingActionButton: FloatingActionButton(
      //   onPressed: () => context.read<${className}Bloc>().add(const Get${className}Event()),
      //   child: const Icon(Icons.refresh),
      // ),
    );
  }
}
''';

  // ─────────────────────────────────────────────
  // PRESENTATION LAYER - Widget
  // ─────────────────────────────────────────────
  static String widget(String name, String className) => '''
// Generated by flutter_clean_architecture_cli
// ─────────────────────────────────────────────────────────────
// ${className}Widget
// Reusable widget for displaying $className data.
// Receives a [${className}Entity] and renders the UI.
// TODO: Build out the UI to match your design.
// ─────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import '../../domain/entities/${name}_entity.dart';

class ${className}Widget extends StatelessWidget {
  final ${className}Entity entity;

  const ${className}Widget({super.key, required this.entity});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // TODO: Replace with your actual UI components
          // This is a placeholder — build your real UI here

          Text(
            'ID: \${entity.id}',
            style: Theme.of(context).textTheme.bodyLarge,
          ),

          // TODO: Display your entity fields
          // Example:
          // Text(
          //   entity.title,
          //   style: Theme.of(context).textTheme.headlineSmall,
          // ),
          // const SizedBox(height: 8),
          // Text(entity.description),

          const SizedBox(height: 24),

          // TODO: Add interactive elements (buttons, forms, lists)
        ],
      ),
    );
  }
}
''';
}
